// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGCpspCq-pHgOYEAQgdAzynjUbj_EOpiQ',
    appId: '1:254841951410:ios:f23ddb0a79694c12bc25ab',
    messagingSenderId: '254841951410',
    projectId: 'my-aiteacher',
    storageBucket: 'my-aiteacher.firebasestorage.app',
    iosBundleId: 'com.myteacher.student',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFI_I2FMYmRrewX8JFKaE9npjqZl5v5ZU',
    appId: '1:254841951410:android:a77950b5810a9573bc25ab',
    messagingSenderId: '254841951410',
    projectId: 'my-aiteacher',
    storageBucket: 'my-aiteacher.firebasestorage.app',
  );
}
